from flask import Flask, render_template, request, jsonify

from detection.url_detector import analyze_url
from detection.file_detector import analyze_file
from detection.email_detector import analyze_email

from core.risk_engine import calculate_unified_risk
from core.correlation_engine import correlate_security_signals
from core.incident_orchestrator import run_incident_orchestration

from graph.knowledge_graph import build_incident_graph

from forensics.evidence_ledger import (
    add_evidence,
    get_evidence,
    verify_ledger
)

import os
import tempfile
import json

from sqlalchemy import text

from database.models import (
    db,
    initialize_database
)

from intelligence.ioc_database import get_ioc_database

try:
    from intelligence import ioc_engine as _ioc_engine_module
except Exception:
    _ioc_engine_module = None


# ============================================================
# APPLICATION
# ============================================================

app = Flask(__name__)


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

BASE_DIR = os.path.abspath(
    os.path.dirname(__file__)
)

DATABASE_DIR = os.path.join(
    BASE_DIR,
    "database"
)

DATABASE_FILE = os.path.join(
    DATABASE_DIR,
    "cybernexus.db"
)

os.makedirs(
    DATABASE_DIR,
    exist_ok=True
)


app.config["SQLALCHEMY_DATABASE_URI"] = (
    "sqlite:///"
    + DATABASE_FILE.replace("\\", "/")
)

app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False


# Initialize database
initialize_database(app)


# ============================================================
# DATABASE HELPERS
# ============================================================

def _get_table_columns(table_name):
    """
    Read SQLite table columns dynamically.

    This keeps database persistence compatible with the
    existing CyberNexus database schema.
    """

    try:

        result = db.session.execute(
            text(
                f"PRAGMA table_info({table_name})"
            )
        )

        rows = result.fetchall()

        return [
            row[1]
            for row in rows
        ]

    except Exception:

        return []


def _safe_json(value):
    """
    Convert Python objects into JSON strings
    when necessary.
    """

    if value is None:
        return None

    if isinstance(
        value,
        (dict, list, tuple)
    ):

        try:

            return json.dumps(
                value,
                ensure_ascii=False
            )

        except Exception:

            return str(value)

    return value


def _insert_matching_columns(
    table_name,
    values
):
    """
    Insert only values whose column names actually
    exist in the SQLite table.

    This prevents database schema mismatch errors.
    """

    columns = _get_table_columns(
        table_name
    )

    if not columns:
        return False

    insert_values = {}

    for key, value in values.items():

        if key in columns:

            insert_values[key] = (
                _safe_json(value)
            )

    if not insert_values:
        return False

    column_names = ", ".join(
        f'"{column}"'
        for column in insert_values.keys()
    )

    parameter_names = ", ".join(
        f":{column}"
        for column in insert_values.keys()
    )

    query = text(
        f"""
        INSERT INTO "{table_name}"
        ({column_names})
        VALUES
        ({parameter_names})
        """
    )

    db.session.execute(
        query,
        insert_values
    )

    return True


def _persist_incident(
    orchestration_result
):
    """
    Persist an incident generated by the
    Incident Orchestrator into SQLite.
    """

    if not isinstance(
        orchestration_result,
        dict
    ):
        return False

    incident = (
        orchestration_result.get(
            "incident"
        )
        or {}
    )

    if not isinstance(
        incident,
        dict
    ):
        incident = {}

    incident_id = (
        incident.get("incident_id")
        or orchestration_result.get(
            "incident_id"
        )
    )

    if not incident_id:
        return False

    try:

        # Prevent duplicate incident records
        columns = _get_table_columns(
            "incidents"
        )

        if "incident_id" in columns:

            existing = db.session.execute(
                text(
                    """
                    SELECT incident_id
                    FROM incidents
                    WHERE incident_id = :incident_id
                    LIMIT 1
                    """
                ),
                {
                    "incident_id":
                        incident_id
                }
            ).fetchone()

            if existing:

                return True

        unified = (
            orchestration_result.get(
                "unified_risk"
            )
            or {}
        )

        correlation = (
            orchestration_result.get(
                "correlation"
            )
            or {}
        )

        values = {

            "incident_id":
                incident_id,

            "incident_level":
                incident.get(
                    "incident_level"
                ),

            "risk_level":
                (
                    unified.get(
                        "overall_level"
                    )
                    if isinstance(
                        unified,
                        dict
                    )
                    else None
                ),

            "risk_score":
                (
                    unified.get(
                        "overall_score"
                    )
                    if isinstance(
                        unified,
                        dict
                    )
                    else None
                ),

            "correlation_score":
                incident.get(
                    "correlation_score"
                ),

            "signal_count":
                incident.get(
                    "signal_count"
                ),

            "high_risk_signal_count":
                incident.get(
                    "high_risk_signal_count"
                ),

            "status":
                "OPEN",

            "severity":
                incident.get(
                    "incident_level"
                ),

            "description":
                (
                    "CyberNexus Ω correlated "
                    "security incident"
                ),

            "data":
                orchestration_result

        }

        # Add correlation values if available
        if isinstance(
            correlation,
            dict
        ):

            values[
                "correlation_score"
            ] = correlation.get(
                "correlation_score",
                values.get(
                    "correlation_score"
                )
            )

        inserted = _insert_matching_columns(
            "incidents",
            values
        )

        if inserted:

            db.session.commit()

        return inserted

    except Exception as error:

        db.session.rollback()

        print(
            "[DATABASE] Incident persistence warning:",
            error
        )

        return False


def _persist_evidence(
    evidence_record
):
    """
    Persist an evidence record into SQLite.

    The original tamper-evident evidence ledger
    continues to operate independently.
    """

    if not isinstance(
        evidence_record,
        dict
    ):
        return False

    try:

        values = {

            "evidence_id":
                evidence_record.get(
                    "evidence_id"
                ),

            "evidence_type":
                evidence_record.get(
                    "evidence_type"
                ),

            "source":
                evidence_record.get(
                    "source"
                ),

            "risk_score":
                evidence_record.get(
                    "risk_score"
                ),

            "risk_level":
                evidence_record.get(
                    "risk_level"
                ),

            "evidence_hash":
                (
                    evidence_record.get(
                        "evidence_hash"
                    )
                    or evidence_record.get(
                        "hash"
                    )
                ),

            "ledger_hash":
                evidence_record.get(
                    "ledger_hash"
                ),

            "data":
                evidence_record

        }

        inserted = _insert_matching_columns(
            "evidence",
            values
        )

        if inserted:

            db.session.commit()

        return inserted

    except Exception as error:

        db.session.rollback()

        print(
            "[DATABASE] Evidence persistence warning:",
            error
        )

        return False



def _update_incident_record(
    orchestration_result
):
    """Update an existing incident with final IOC enrichment."""

    if not isinstance(orchestration_result, dict):
        return False

    incident = orchestration_result.get("incident") or {}
    if not isinstance(incident, dict):
        incident = {}

    incident_id = (
        incident.get("incident_id")
        or orchestration_result.get("incident_id")
    )

    if not incident_id:
        return False

    unified = orchestration_result.get("unified_risk") or {}
    correlation = orchestration_result.get("correlation") or {}

    values = {
        "incident_level": incident.get("incident_level"),
        "risk_level": unified.get("overall_level") if isinstance(unified, dict) else None,
        "risk_score": unified.get("overall_score") if isinstance(unified, dict) else None,
        "correlation_score": correlation.get("correlation_score") if isinstance(correlation, dict) else incident.get("correlation_score"),
        "signal_count": incident.get("signal_count"),
        "high_risk_signal_count": incident.get("high_risk_signal_count"),
        "status": incident.get("status") or "OPEN",
        "severity": incident.get("incident_level"),
        "description": incident.get("description", "CyberNexus Ω correlated security incident"),
        "data": orchestration_result
    }

    try:
        columns = _get_table_columns("incidents")
        if not columns:
            return False

        assignments = []
        parameters = {"incident_id": incident_id}

        for key, value in values.items():
            if key in columns:
                assignments.append(f'"{key}" = :{key}')
                parameters[key] = _safe_json(value)

        if not assignments:
            return False

        query = text(
            f"""
            UPDATE "incidents"
            SET {", ".join(assignments)}
            WHERE "incident_id" = :incident_id
            """
        )

        db.session.execute(query, parameters)
        db.session.commit()
        return True

    except Exception as error:
        db.session.rollback()
        print("[DATABASE] Incident update warning:", error)
        return False


# ============================================================
# IOC / THREAT INTELLIGENCE HELPERS
# ============================================================

IOC_DATABASE = get_ioc_database(
    database_path=DATABASE_FILE
)


def _get_latest_database_incident_id(incident_id=None):
    """
    Resolve the integer SQLite incident primary key required by
    the existing iocs schema.
    """
    try:
        if incident_id:
            row = db.session.execute(
                text(
                    """
                    SELECT id
                    FROM incidents
                    WHERE incident_id = :incident_id
                    ORDER BY id DESC
                    LIMIT 1
                    """
                ),
                {"incident_id": incident_id}
            ).fetchone()

            if row:
                return int(row[0])

        row = db.session.execute(
            text(
                """
                SELECT id
                FROM incidents
                ORDER BY id DESC
                LIMIT 1
                """
            )
        ).fetchone()

        if row:
            return int(row[0])

    except Exception as error:
        print(
            "[IOC] Incident lookup warning:",
            error
        )

    return None


def _normalize_ioc_type(ioc_type):
    value = str(ioc_type or "").strip().upper()

    aliases = {
        "URL": "URL",
        "URI": "URL",
        "DOMAIN": "DOMAIN",
        "HOSTNAME": "DOMAIN",
        "IP": "IP",
        "IPV4": "IP",
        "IPV6": "IP",
        "EMAIL": "EMAIL",
        "EMAIL_ADDRESS": "EMAIL",
        "MD5": "MD5",
        "SHA1": "SHA1",
        "SHA-1": "SHA1",
        "SHA256": "SHA256",
        "SHA-256": "SHA256",
    }

    return aliases.get(value, value)


def _clean_ioc_values(values):
    if values is None:
        return []

    if isinstance(values, str):
        values = [values]

    if not isinstance(values, (list, tuple, set)):
        return []

    cleaned = []

    for value in values:
        value = str(value).strip()

        if value and value not in cleaned:
            cleaned.append(value)

    return cleaned


def _fallback_extract_iocs(text_value):
    """
    Local compatibility extractor used only when the dedicated
    IOC engine cannot be called through its exposed API.
    """
    import re

    text_value = str(text_value or "")

    found = {
        "urls": [],
        "domains": [],
        "ips": [],
        "emails": [],
        "hashes": {
            "md5": [],
            "sha1": [],
            "sha256": []
        }
    }

    url_pattern = re.compile(
        r"https?://[^\s<>'\"`]+",
        re.IGNORECASE
    )

    email_pattern = re.compile(
        r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b",
        re.IGNORECASE
    )

    ipv4_pattern = re.compile(
        r"\b(?:\d{1,3}\.){3}\d{1,3}\b"
    )

    sha256_pattern = re.compile(
        r"\b[a-fA-F0-9]{64}\b"
    )

    sha1_pattern = re.compile(
        r"\b[a-fA-F0-9]{40}\b"
    )

    md5_pattern = re.compile(
        r"\b[a-fA-F0-9]{32}\b"
    )

    domain_pattern = re.compile(
        r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}"
        r"[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}\b"
    )

    for value in url_pattern.findall(text_value):
        value = value.rstrip(".,;:)]}")
        if value not in found["urls"]:
            found["urls"].append(value)

    for value in email_pattern.findall(text_value):
        if value not in found["emails"]:
            found["emails"].append(value)

    for value in ipv4_pattern.findall(text_value):
        parts = value.split(".")

        if all(
            0 <= int(part) <= 255
            for part in parts
        ):
            if value not in found["ips"]:
                found["ips"].append(value)

    for value in sha256_pattern.findall(text_value):
        value = value.lower()
        if value not in found["hashes"]["sha256"]:
            found["hashes"]["sha256"].append(value)

    for value in sha1_pattern.findall(text_value):
        value = value.lower()

        if value not in found["hashes"]["sha1"]:
            found["hashes"]["sha1"].append(value)

    for value in md5_pattern.findall(text_value):
        value = value.lower()

        if value not in found["hashes"]["md5"]:
            found["hashes"]["md5"].append(value)

    for value in domain_pattern.findall(text_value):
        if value in found["ips"]:
            continue

        if value.lower() in {
            item.lower()
            for item in found["emails"]
        }:
            continue

        if value not in found["domains"]:
            found["domains"].append(value)

    return found


def _engine_result_to_iocs(result):
    """
    Normalize common IOC-engine output shapes into one structure.
    """
    empty = {
        "urls": [],
        "domains": [],
        "ips": [],
        "emails": [],
        "hashes": {
            "md5": [],
            "sha1": [],
            "sha256": []
        }
    }

    if not isinstance(result, dict):
        return empty

    source = result.get("iocs")

    if isinstance(source, dict):
        result = source

    urls = (
        result.get("urls")
        or result.get("URLS")
        or result.get("url")
        or []
    )

    domains = (
        result.get("domains")
        or result.get("DOMAIN")
        or []
    )

    ips = (
        result.get("ips")
        or result.get("IP")
        or []
    )

    emails = (
        result.get("emails")
        or result.get("EMAILS")
        or result.get("email")
        or []
    )

    hashes = (
        result.get("hashes")
        or result.get("HASHES")
        or {}
    )

    if not isinstance(hashes, dict):
        hashes = {}

    empty["urls"] = _clean_ioc_values(urls)
    empty["domains"] = _clean_ioc_values(domains)
    empty["ips"] = _clean_ioc_values(ips)
    empty["emails"] = _clean_ioc_values(emails)

    empty["hashes"]["md5"] = _clean_ioc_values(
        hashes.get("md5")
        or hashes.get("MD5")
    )

    empty["hashes"]["sha1"] = _clean_ioc_values(
        hashes.get("sha1")
        or hashes.get("SHA1")
        or hashes.get("sha-1")
    )

    empty["hashes"]["sha256"] = _clean_ioc_values(
        hashes.get("sha256")
        or hashes.get("SHA256")
        or hashes.get("sha-256")
    )

    return empty


def _extract_iocs(text_value):
    """
    Use the dedicated IOC engine when one of its common public
    interfaces is available. Otherwise use the safe local fallback.
    """
    fallback = _fallback_extract_iocs(
        text_value
    )

    if _ioc_engine_module is None:
        return fallback

    candidates = []

    for function_name in (
        "extract_iocs",
        "extract_all_iocs",
        "parse_iocs",
        "analyze_iocs",
        "extract",
        "analyze",
    ):
        function = getattr(
            _ioc_engine_module,
            function_name,
            None
        )

        if callable(function):
            candidates.append(function)

    for function in candidates:
        try:
            result = function(
                text_value
            )

            normalized = _engine_result_to_iocs(
                result
            )

            if any([
                normalized["urls"],
                normalized["domains"],
                normalized["ips"],
                normalized["emails"],
                normalized["hashes"]["md5"],
                normalized["hashes"]["sha1"],
                normalized["hashes"]["sha256"],
            ]):
                return normalized

        except Exception:
            continue

    return fallback


def _collect_ioc_source_text(
    url_result=None,
    file_result=None,
    email_result=None
):
    """
    Convert detector outputs into text that can be processed by
    the IOC engine.
    """
    parts = []

    for result in (
        url_result,
        file_result,
        email_result
    ):
        if result is None:
            continue

        if isinstance(result, str):
            parts.append(result)

        elif isinstance(result, dict):
            try:
                parts.append(
                    json.dumps(
                        result,
                        ensure_ascii=False
                    )
                )
            except Exception:
                parts.append(
                    str(result)
                )

        else:
            parts.append(
                str(result)
            )

    return "\n".join(parts)


def _ioc_items_from_results(
    url_result=None,
    file_result=None,
    email_result=None
):
    """
    Extract IOCs from detector results.
    Also explicitly adds detector-provided URLs and hashes so
    structured detector outputs are not lost.
    """
    source_text = _collect_ioc_source_text(
        url_result=url_result,
        file_result=file_result,
        email_result=email_result
    )

    extracted = _extract_iocs(
        source_text
    )

    items = []

    def add_item(
        ioc_type,
        value,
        confidence,
        source
    ):
        value = str(value or "").strip()

        if not value:
            return

        normalized_type = _normalize_ioc_type(
            ioc_type
        )

        key = (
            normalized_type,
            value.lower()
        )

        if any(
            item["_key"] == key
            for item in items
        ):
            return

        items.append({
            "_key": key,
            "ioc_type": normalized_type,
            "value": value,
            "confidence": int(
                max(
                    0,
                    min(
                        100,
                        int(confidence)
                    )
                )
            ),
            "source": source
        })

    for value in extracted["urls"]:
        add_item(
            "URL",
            value,
            85,
            "IOC Engine"
        )

    for value in extracted["domains"]:
        add_item(
            "DOMAIN",
            value,
            80,
            "IOC Engine"
        )

    for value in extracted["ips"]:
        add_item(
            "IP",
            value,
            80,
            "IOC Engine"
        )

    for value in extracted["emails"]:
        add_item(
            "EMAIL",
            value,
            75,
            "IOC Engine"
        )

    for value in extracted["hashes"]["md5"]:
        add_item(
            "MD5",
            value,
            90,
            "IOC Engine"
        )

    for value in extracted["hashes"]["sha1"]:
        add_item(
            "SHA1",
            value,
            90,
            "IOC Engine"
        )

    for value in extracted["hashes"]["sha256"]:
        add_item(
            "SHA256",
            value,
            95,
            "IOC Engine"
        )

    # Detector-specific structured values.
    if isinstance(url_result, dict):
        for key in (
            "url",
            "normalized_url",
            "final_url"
        ):
            if url_result.get(key):
                add_item(
                    "URL",
                    url_result.get(key),
                    90,
                    "URL Detector"
                )

        for key in (
            "domain",
            "hostname"
        ):
            if url_result.get(key):
                add_item(
                    "DOMAIN",
                    url_result.get(key),
                    85,
                    "URL Detector"
                )

        for key in (
            "ip",
            "ip_address"
        ):
            if url_result.get(key):
                add_item(
                    "IP",
                    url_result.get(key),
                    85,
                    "URL Detector"
                )

    if isinstance(file_result, dict):
        for key, ioc_type, confidence in (
            ("md5", "MD5", 90),
            ("sha1", "SHA1", 92),
            ("sha256", "SHA256", 95)
        ):
            if file_result.get(key):
                add_item(
                    ioc_type,
                    file_result.get(key),
                    confidence,
                    "File Detector"
                )

    if isinstance(email_result, dict):
        for key in (
            "sender",
            "from",
            "sender_email"
        ):
            if email_result.get(key):
                add_item(
                    "EMAIL",
                    email_result.get(key),
                    85,
                    "Email Detector"
                )

    return items


def _persist_iocs(
    url_result=None,
    file_result=None,
    email_result=None,
    incident_id=None
):
    """
    Store extracted IOCs in the existing IOC database and return
    a complete integration summary.
    """
    items = _ioc_items_from_results(
        url_result=url_result,
        file_result=file_result,
        email_result=email_result
    )

    database_incident_id = (
        _get_latest_database_incident_id(
            incident_id=incident_id
        )
    )

    summary = {
        "enabled": True,
        "incident_id": incident_id,
        "database_incident_id": database_incident_id,
        "extracted_count": len(items),
        "created_count": 0,
        "known_count": 0,
        "records": [],
        "status": "not_stored"
    }

    if database_incident_id is None:
        summary["status"] = (
            "no_incident_record_available"
        )

        return summary

    for item in items:
        try:
            existing = IOC_DATABASE.get_ioc(
                item["ioc_type"],
                item["value"]
            )

            if existing:
                summary["known_count"] += 1

                summary["records"].append({
                    "ioc_type": item["ioc_type"],
                    "value": item["value"],
                    "known": True,
                    "created": False,
                    "ioc": existing
                })

                continue

            result = IOC_DATABASE.add_ioc(
                ioc_type=item["ioc_type"],
                incident_id=database_incident_id,
                value=item["value"],
                confidence=item["confidence"],
                source=item["source"]
            )

            created = bool(
                isinstance(result, dict)
                and result.get("created")
            )

            if created:
                summary["created_count"] += 1

            summary["records"].append({
                "ioc_type": item["ioc_type"],
                "value": item["value"],
                "known": False,
                "created": created,
                "ioc": (
                    result.get("ioc")
                    if isinstance(result, dict)
                    else None
                )
            })

        except Exception as error:
            summary["records"].append({
                "ioc_type": item["ioc_type"],
                "value": item["value"],
                "known": False,
                "created": False,
                "error": str(error)
            })

    summary["status"] = "stored"

    return summary



# ============================================================
# IOC → RISK CORRELATION HELPERS
# ============================================================

def _ioc_risk_weight(ioc_type):
    """
    Base threat-intelligence weight for a known IOC type.
    """
    weights = {
        "URL": 90,
        "DOMAIN": 85,
        "IP": 82,
        "EMAIL": 70,
        "MD5": 88,
        "SHA1": 92,
        "SHA256": 95,
    }
    return weights.get(
        _normalize_ioc_type(ioc_type),
        70
    )


def _calculate_ioc_risk_intelligence(ioc_summary):
    """
    Convert IOC database matches and confidence into a normalized
    threat-intelligence contribution.

    This layer does not replace the existing Risk Engine. It adds
    an explicit IOC intelligence signal that can be consumed by
    the incident/correlation pipeline.
    """
    if not isinstance(ioc_summary, dict):
        return {
            "enabled": True,
            "matched_count": 0,
            "average_confidence": 0,
            "threat_intelligence_score": 0,
            "risk_bonus": 0,
            "risk_level": "LOW",
            "signals": [],
        }

    records = ioc_summary.get("records") or []

    matched = []
    for record in records:
        if not isinstance(record, dict):
            continue

        ioc = record.get("ioc") or {}
        known = bool(record.get("known"))

        if not known or not isinstance(ioc, dict):
            continue

        confidence = ioc.get("confidence", 0)
        try:
            confidence = max(0, min(100, int(confidence)))
        except (TypeError, ValueError):
            confidence = 0

        ioc_type = _normalize_ioc_type(
            record.get("ioc_type") or ioc.get("ioc_type")
        )

        weight = _ioc_risk_weight(ioc_type)

        # Confidence and IOC-type criticality are combined.
        intelligence_score = round(
            (confidence * 0.7) + (weight * 0.3)
        )

        matched.append({
            "ioc_type": ioc_type,
            "value": record.get("value") or ioc.get("value"),
            "confidence": confidence,
            "type_weight": weight,
            "intelligence_score": intelligence_score,
            "source": ioc.get("source"),
        })

    if not matched:
        return {
            "enabled": True,
            "matched_count": 0,
            "average_confidence": 0,
            "threat_intelligence_score": 0,
            "risk_bonus": 0,
            "risk_level": "LOW",
            "signals": [],
        }

    average_confidence = round(
        sum(item["confidence"] for item in matched)
        / len(matched)
    )

    threat_intelligence_score = round(
        sum(item["intelligence_score"] for item in matched)
        / len(matched)
    )

    # Multiple known IOCs increase the correlation contribution,
    # while keeping the bonus bounded.
    risk_bonus = min(
        35,
        round(
            (threat_intelligence_score * 0.20)
            + ((len(matched) - 1) * 5)
        )
    )

    if threat_intelligence_score >= 85:
        risk_level = "CRITICAL"
    elif threat_intelligence_score >= 70:
        risk_level = "HIGH"
    elif threat_intelligence_score >= 40:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    return {
        "enabled": True,
        "matched_count": len(matched),
        "average_confidence": average_confidence,
        "threat_intelligence_score": threat_intelligence_score,
        "risk_bonus": risk_bonus,
        "risk_level": risk_level,
        "signals": matched,
    }


def _apply_ioc_risk_to_result(
    orchestration_result,
    ioc_intelligence
):
    """
    Attach IOC intelligence to the existing incident result and
    calculate an IOC-adjusted risk score without destroying the
    original Risk Engine score.
    """
    if not isinstance(orchestration_result, dict):
        return orchestration_result

    if not isinstance(ioc_intelligence, dict):
        return orchestration_result

    unified = orchestration_result.get("unified_risk")

    if not isinstance(unified, dict):
        unified = {}

    original_score = unified.get("overall_score", 0)

    try:
        original_score = max(
            0,
            min(100, int(original_score))
        )
    except (TypeError, ValueError):
        original_score = 0

    risk_bonus = ioc_intelligence.get(
        "risk_bonus",
        0
    )

    try:
        risk_bonus = max(
            0,
            min(35, int(risk_bonus))
        )
    except (TypeError, ValueError):
        risk_bonus = 0

    adjusted_score = min(
        100,
        original_score + risk_bonus
    )

    if adjusted_score >= 80:
        adjusted_level = "CRITICAL"
    elif adjusted_score >= 60:
        adjusted_level = "HIGH"
    elif adjusted_score >= 30:
        adjusted_level = "MEDIUM"
    else:
        adjusted_level = "LOW"

    unified["original_score"] = original_score
    unified["ioc_risk_bonus"] = risk_bonus
    unified["overall_score_before_ioc"] = original_score
    unified["overall_score"] = adjusted_score
    unified["overall_level_before_ioc"] = unified.get(
        "overall_level",
        "LOW"
    )
    unified["overall_level"] = adjusted_level
    unified["ioc_adjusted"] = True

    orchestration_result["unified_risk"] = unified
    orchestration_result["ioc_intelligence"] = ioc_intelligence

    incident = orchestration_result.get("incident")

    if isinstance(incident, dict):
        incident["risk_score_before_ioc"] = original_score
        incident["ioc_risk_bonus"] = risk_bonus
        incident["risk_score"] = adjusted_score
        incident["incident_level_before_ioc"] = incident.get(
            "incident_level"
        )

        if adjusted_score >= 80:
            incident["incident_level"] = "CRITICAL"
        elif adjusted_score >= 60:
            incident["incident_level"] = "HIGH"
        elif adjusted_score >= 30:
            incident["incident_level"] = "MEDIUM"
        else:
            incident["incident_level"] = "LOW"

    return orchestration_result

# ============================================================
# DASHBOARD
# ============================================================

@app.route("/")
def dashboard():

    return render_template(
        "dashboard.html"
    )


# ============================================================
# HEALTH
# ============================================================

@app.route("/health")
def health():

    database_status = "unknown"

    try:

        db.session.execute(
            text("SELECT 1")
        )

        database_status = "connected"

    except Exception:

        database_status = "error"

    return jsonify({

        "status":
            "operational",

        "system":
            "CYBERNEXUS Ω",

        "version":
            "1.0.0",

        "database":
            database_status

    })


# ============================================================
# API INFORMATION
# ============================================================

@app.route("/api")
def api_info():

    return jsonify({

        "system":
            "CYBERNEXUS Ω",

        "status":
            "operational",

        "database":
            "SQLite",

        "database_file":
            "database/cybernexus.db",

        "endpoints": {

            "health":
                "/health",

            "url_analysis":
                "/api/analyze-url",

            "file_analysis":
                "/api/analyze-file",

            "email_analysis":
                "/api/analyze-email",

            "unified_risk":
                "/api/unified-risk",

            "correlation":
                "/api/correlate",

            "incident":
                "/api/incident",

            "graph":
                "/api/graph",

            "add_evidence":
                "/api/evidence",

            "get_evidence":
                "/api/evidence",

            "verify_evidence":
                "/api/evidence/verify",

            "ioc":
                "/api/ioc",

            "incident_details":
                "/api/incident/<incident_id>"

        }

    })


# ============================================================
# URL ANALYSIS
# ============================================================

@app.route(
    "/api/analyze-url",
    methods=["POST"]
)
def analyze_url_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url = (
        data.get(
            "url",
            ""
        )
        .strip()
    )

    if not url:

        return jsonify({

            "success":
                False,

            "error":
                "URL is required."

        }), 400

    try:

        result = analyze_url(
            url
        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# FILE ANALYSIS
# ============================================================

@app.route(
    "/api/analyze-file",
    methods=["POST"]
)
def analyze_file_api():

    if "file" not in request.files:

        return jsonify({

            "success":
                False,

            "error":
                "No file uploaded."

        }), 400

    uploaded_file = (
        request.files["file"]
    )

    if not uploaded_file.filename:

        return jsonify({

            "success":
                False,

            "error":
                "Filename is missing."

        }), 400

    temp_path = None

    try:

        suffix = os.path.splitext(
            uploaded_file.filename
        )[1]

        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=suffix
        ) as temp_file:

            uploaded_file.save(
                temp_file.name
            )

            temp_path = (
                temp_file.name
            )

        result = analyze_file(
            temp_path
        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500

    finally:

        if (
            temp_path
            and os.path.exists(
                temp_path
            )
        ):

            try:

                os.remove(
                    temp_path
                )

            except OSError:

                pass


# ============================================================
# EMAIL ANALYSIS
# ============================================================

@app.route(
    "/api/analyze-email",
    methods=["POST"]
)
def analyze_email_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    email_text = data.get(
        "email",
        ""
    )

    sender = data.get(
        "sender"
    )

    if not email_text:

        return jsonify({

            "success":
                False,

            "error":
                "Email content is required."

        }), 400

    try:

        result = analyze_email(
            email_text,
            sender
        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# UNIFIED RISK
# ============================================================

@app.route(
    "/api/unified-risk",
    methods=["POST"]
)
def unified_risk_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    try:

        result = calculate_unified_risk(

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# CORRELATION ENGINE
# ============================================================

@app.route(
    "/api/correlate",
    methods=["POST"]
)
def correlate_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    try:

        result = correlate_security_signals(

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# INCIDENT ORCHESTRATOR
# ============================================================

@app.route(
    "/api/incident",
    methods=["POST"]
)
def incident_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    if not any([

        url_result,
        file_result,
        email_result

    ]):

        return jsonify({

            "success":
                False,

            "error":
                "At least one security signal is required."

        }), 400

    try:

        result = run_incident_orchestration(

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        # ====================================================
        # IOC / THREAT INTELLIGENCE INTEGRATION
        # ====================================================

        incident_identifier = None

        if isinstance(result, dict):
            incident_data = (
                result.get("incident")
                or {}
            )

            if isinstance(
                incident_data,
                dict
            ):
                incident_identifier = (
                    incident_data.get(
                        "incident_id"
                    )
                )

            if not incident_identifier:
                incident_identifier = (
                    result.get(
                        "incident_id"
                    )
                )

        # STEP 1: Create the incident row FIRST so IOC records receive
        # the correct database incident primary key.
        database_saved = _persist_incident(result)

        # STEP 2: Store IOCs against THIS incident.
        ioc_result = _persist_iocs(
            url_result=url_result,
            file_result=file_result,
            email_result=email_result,
            incident_id=incident_identifier
        )

        # STEP 3: Calculate IOC threat-intelligence impact.
        ioc_intelligence = _calculate_ioc_risk_intelligence(ioc_result)

        result = _apply_ioc_risk_to_result(
            result,
            ioc_intelligence
        )

        # STEP 4: Store enrichment in the incident payload.
        if isinstance(result, dict):
            result["ioc_intelligence"] = ioc_intelligence
            result["ioc_storage"] = ioc_result

        # STEP 5: Update the SAME incident row with final risk + enrichment.
        database_updated = _update_incident_record(result)

        if isinstance(result, dict):
            result["database"] = {
                "saved": database_saved,
                "updated": database_updated,
                "database_file": "database/cybernexus.db"
            }

        return jsonify(
            result
        )

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# INCIDENT INVESTIGATION DETAILS
# ============================================================

@app.route(
    "/api/incident/<incident_id>",
    methods=["GET"]
)
def incident_details_api(incident_id):

    incident_id = str(incident_id or "").strip()

    if not incident_id:
        return jsonify({
            "success": False,
            "error": "Incident ID is required."
        }), 400

    try:
        incident_columns = _get_table_columns("incidents")

        if not incident_columns:
            return jsonify({
                "success": False,
                "error": "Incidents table is unavailable."
            }), 500

        selected_columns = [
            column
            for column in (
                "id", "incident_id", "incident_level",
                "risk_level", "risk_score", "correlation_score",
                "signal_count", "high_risk_signal_count",
                "status", "severity", "description",
                "data", "created_at"
            )
            if column in incident_columns
        ]

        if "incident_id" not in selected_columns:
            return jsonify({
                "success": False,
                "error": "Incident ID column is unavailable."
            }), 500

        column_sql = ", ".join(
            '"' + column + '"'
            for column in selected_columns
        )
        order_column = (
            '"id"'
            if "id" in incident_columns
            else 'rowid'
        )

        query = text(
            f"""
            SELECT {column_sql}
            FROM incidents
            WHERE "incident_id" = :incident_id
            ORDER BY {order_column} DESC
            LIMIT 1
            """
        )

        row = db.session.execute(
            query,
            {"incident_id": incident_id}
        ).fetchone()

        if not row:
            return jsonify({
                "success": False,
                "error": "Incident not found.",
                "incident_id": incident_id
            }), 404

        incident = {
            column: row[index]
            for index, column in enumerate(selected_columns)
        }

        payload = incident.get("data")
        if isinstance(payload, str) and payload.strip():
            try:
                payload = json.loads(payload)
            except Exception:
                payload = None
        elif not isinstance(payload, dict):
            payload = None

        unified_risk = {}
        correlation = {}
        ioc_intelligence = {}
        ioc_storage = {}
        graph = {}
        evidence = []

        if isinstance(payload, dict):
            unified_risk = payload.get("unified_risk") or {}
            correlation = payload.get("correlation") or {}
            ioc_intelligence = payload.get("ioc_intelligence") or {}
            ioc_storage = payload.get("ioc_storage") or {}
            graph = payload.get("graph") or {}
            evidence_value = payload.get("evidence")

            if isinstance(evidence_value, list):
                evidence = evidence_value
            elif isinstance(evidence_value, dict):
                evidence = [evidence_value]

            incident_payload = payload.get("incident") or {}
            if isinstance(incident_payload, dict):
                if not graph:
                    graph = incident_payload.get("graph") or {}
                if not evidence:
                    evidence_value = incident_payload.get("evidence")
                    if isinstance(evidence_value, list):
                        evidence = evidence_value
                    elif isinstance(evidence_value, dict):
                        evidence = [evidence_value]

        database_incident_id = incident.get("id")
        ioc_records = []

        if database_incident_id is not None:
            ioc_columns = _get_table_columns("iocs")

            if ioc_columns and "incident_id" in ioc_columns:
                ioc_select = [
                    column
                    for column in (
                        "id", "ioc_type", "value",
                        "confidence", "source", "created_at"
                    )
                    if column in ioc_columns
                ]

                if ioc_select:
                    ioc_column_sql = ", ".join(
                        '"' + column + '"'
                        for column in ioc_select
                    )
                    ioc_order = (
                        '"id"'
                        if "id" in ioc_columns
                        else 'rowid'
                    )
                    ioc_query = text(
                        f"""
                        SELECT {ioc_column_sql}
                        FROM iocs
                        WHERE "incident_id" = :incident_id
                        ORDER BY {ioc_order} DESC
                        """
                    )
                    ioc_rows = db.session.execute(
                        ioc_query,
                        {"incident_id": database_incident_id}
                    ).fetchall()

                    for ioc_row in ioc_rows:
                        ioc_records.append({
                            column: ioc_row[index]
                            for index, column in enumerate(ioc_select)
                        })

        if not ioc_records and isinstance(ioc_storage, dict):
            stored_records = ioc_storage.get("records") or []
            if isinstance(stored_records, list):
                for record in stored_records:
                    if not isinstance(record, dict):
                        continue
                    ioc = record.get("ioc")
                    if isinstance(ioc, dict):
                        ioc_records.append({
                            "ioc_type": record.get("ioc_type") or ioc.get("ioc_type"),
                            "value": record.get("value") or ioc.get("value"),
                            "confidence": ioc.get("confidence"),
                            "source": ioc.get("source")
                        })

        graph_nodes = graph.get("nodes", []) if isinstance(graph, dict) else []
        graph_edges = graph.get("edges", []) if isinstance(graph, dict) else []

        return jsonify({
            "success": True,
            "incident": {
                "incident_id": incident.get("incident_id", incident_id),
                "incident_level": incident.get("incident_level"),
                "risk_level": incident.get("risk_level"),
                "risk_score": incident.get("risk_score"),
                "correlation_score": incident.get("correlation_score"),
                "signal_count": incident.get("signal_count"),
                "high_risk_signal_count": incident.get("high_risk_signal_count"),
                "status": incident.get("status"),
                "severity": incident.get("severity"),
                "description": incident.get("description"),
                "created_at": incident.get("created_at")
            },
            "risk": unified_risk if isinstance(unified_risk, dict) else {},
            "correlation": correlation if isinstance(correlation, dict) else {},
            "ioc_intelligence": ioc_intelligence if isinstance(ioc_intelligence, dict) else {},
            "iocs": {
                "count": len(ioc_records),
                "records": ioc_records
            },
            "evidence": {
                "count": len(evidence),
                "records": evidence
            },
            "graph": {
                "nodes": graph_nodes if isinstance(graph_nodes, list) else [],
                "edges": graph_edges if isinstance(graph_edges, list) else [],
                "node_count": len(graph_nodes) if isinstance(graph_nodes, list) else 0,
                "edge_count": len(graph_edges) if isinstance(graph_edges, list) else 0
            },
            "database": {
                "incident_row_id": database_incident_id
            }
        })

    except Exception as error:
        return jsonify({
            "success": False,
            "error": str(error),
            "incident_id": incident_id
        }), 500


# ============================================================
# KNOWLEDGE GRAPH
# ============================================================

@app.route(
    "/api/graph",
    methods=["POST"]
)
def graph_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    incident_id = data.get(

        "incident_id",

        "UNKNOWN-INCIDENT"

    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    try:

        graph = build_incident_graph(

            incident_id=
                incident_id,

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        return jsonify({

            "success":
                True,

            "result":
                graph

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# ADD EVIDENCE
# ============================================================

@app.route(
    "/api/evidence",
    methods=["POST"]
)
def add_evidence_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    evidence_type = data.get(

        "evidence_type",

        "UNKNOWN"

    )

    source = data.get(

        "source",

        "Unknown"

    )

    evidence = data.get(

        "evidence",

        {}

    )

    risk_score = data.get(

        "risk_score",

        0

    )

    risk_level = data.get(

        "risk_level",

        "LOW"

    )

    try:

        record = add_evidence(

            evidence_type=
                evidence_type,

            source=
                source,

            evidence=
                evidence,

            risk_score=
                risk_score,

            risk_level=
                risk_level

        )

        database_saved = (
            _persist_evidence(
                record
            )
        )

        return jsonify({

            "success":
                True,

            "record":
                record,

            "database":
                {

                    "saved":
                        database_saved,

                    "database_file":
                        "database/cybernexus.db"

                }

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# GET EVIDENCE
# ============================================================

@app.route(
    "/api/evidence",
    methods=["GET"]
)
def get_evidence_api():

    try:

        records = get_evidence()

        return jsonify({

            "success":
                True,

            "records":
                records,

            "count":
                len(records)

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# VERIFY EVIDENCE
# ============================================================

@app.route(
    "/api/evidence/verify",
    methods=["GET"]
)
def verify_evidence_api():

    try:

        result = verify_ledger()

        return jsonify({

            "success":
                True,

            "verification":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500



# ============================================================
# IOC / THREAT INTELLIGENCE API
# ============================================================

@app.route(
    "/api/ioc",
    methods=["GET", "POST"]
)
def ioc_api():

    if request.method == "GET":

        value = request.args.get(
            "value",
            ""
        ).strip()

        ioc_type = request.args.get(
            "ioc_type"
        )

        try:
            if value:
                record = IOC_DATABASE.get_ioc(
                    ioc_type or "DOMAIN",
                    value
                )

                return jsonify({
                    "success": True,
                    "found": record is not None,
                    "record": record,
                    "count": (
                        1
                        if record
                        else 0
                    )
                })

            records = IOC_DATABASE.search(
                value="",
                ioc_type=ioc_type
            )

            return jsonify({
                "success": True,
                "records": records,
                "count": len(records),
                "total_iocs": IOC_DATABASE.count()
            })

        except Exception as error:

            return jsonify({
                "success": False,
                "error": str(error)
            }), 500

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    text_value = data.get(
        "text"
    )

    incident_id = data.get(
        "incident_id"
    )

    # Direct text input is supported for IOC extraction tests and
    # threat-intelligence ingestion. The existing structured detector
    # result inputs remain fully supported.
    if (
        isinstance(text_value, str)
        and text_value.strip()
        and not any([
            url_result,
            file_result,
            email_result
        ])
    ):
        url_result = text_value.strip()

    try:
        result = _persist_iocs(
            url_result=url_result,
            file_result=file_result,
            email_result=email_result,
            incident_id=incident_id
        )

        return jsonify({
            "success": True,
            "result": result
        })

    except Exception as error:

        return jsonify({
            "success": False,
            "error": str(error)
        }), 500


# ============================================================
# DATABASE STATUS
# ============================================================

@app.route(
    "/api/database",
    methods=["GET"]
)
def database_status_api():

    try:

        tables = []

        result = db.session.execute(
            text(
                """
                SELECT name
                FROM sqlite_master
                WHERE type='table'
                ORDER BY name
                """
            )
        )

        for row in result.fetchall():

            tables.append(
                row[0]
            )

        return jsonify({

            "success":
                True,

            "database":
                "SQLite",

            "file":
                DATABASE_FILE,

            "status":
                "connected",

            "tables":
                tables

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "database":
                "SQLite",

            "status":
                "error",

            "error":
                str(error)

        }), 500

# ============================================================
# LIVE SOC METRICS
# ============================================================

@app.route(
    "/api/soc-metrics",
    methods=["GET"]
)
def soc_metrics_api():

    try:
        incident_count = 0
        critical_count = 0
        high_count = 0
        medium_count = 0
        low_count = 0

        incident_columns = _get_table_columns("incidents")

        if incident_columns:
            row = db.session.execute(
                text('SELECT COUNT(*) FROM "incidents"')
            ).fetchone()
            incident_count = int(row[0] or 0)

            if "risk_level" in incident_columns:
                rows = db.session.execute(
                    text("""
                        SELECT risk_level, COUNT(*)
                        FROM incidents
                        GROUP BY risk_level
                    """)
                ).fetchall()

                for level, count in rows:
                    level = str(level or "").upper()
                    if level == "CRITICAL":
                        critical_count = int(count)
                    elif level == "HIGH":
                        high_count = int(count)
                    elif level == "MEDIUM":
                        medium_count = int(count)
                    elif level == "LOW":
                        low_count = int(count)

        ioc_count = 0
        ioc_columns = _get_table_columns("iocs")
        if ioc_columns:
            row = db.session.execute(
                text('SELECT COUNT(*) FROM "iocs"')
            ).fetchone()
            ioc_count = int(row[0] or 0)

        evidence_count = 0
        evidence_columns = _get_table_columns("evidence")
        if evidence_columns:
            row = db.session.execute(
                text('SELECT COUNT(*) FROM "evidence"')
            ).fetchone()
            evidence_count = int(row[0] or 0)

        recent_incidents = []

        if incident_columns:
            wanted = (
                "incident_id",
                "risk_level",
                "risk_score",
                "incident_level",
                "correlation_score",
                "status"
            )

            select_columns = [
                f'"{column}"'
                for column in wanted
                if column in incident_columns
            ]

            if "id" in incident_columns:
                order_column = '"id"'
            elif "created_at" in incident_columns:
                order_column = '"created_at"'
            else:
                order_column = 'rowid'

            if select_columns:
                query = f"""
                    SELECT {", ".join(select_columns)}
                    FROM incidents
                    ORDER BY {order_column} DESC
                    LIMIT 10
                """

                rows = db.session.execute(text(query)).fetchall()
                selected_names = [
                    column.strip('"')
                    for column in select_columns
                ]

                for row in rows:
                    record = {}
                    for index, name in enumerate(selected_names):
                        value = row[index]
                        if hasattr(value, "isoformat"):
                            value = value.isoformat()
                        record[name] = value
                    recent_incidents.append(record)

        return jsonify({
            "success": True,
            "metrics": {
                "total_incidents": incident_count,
                "critical": critical_count,
                "high": high_count,
                "medium": medium_count,
                "low": low_count,
                "total_iocs": ioc_count,
                "total_evidence": evidence_count
            },
            "recent_incidents": recent_incidents,
            "system": "CYBERNEXUS Ω",
            "status": "operational"
        })

    except Exception as error:
        return jsonify({
            "success": False,
            "error": str(error),
            "system": "CYBERNEXUS Ω",
            "status": "degraded"
        }), 500



# ============================================================
# STEP 25 - SOC ANALYTICS & SECURITY REPORTING
# ============================================================

@app.route(
    "/api/soc-analytics",
    methods=["GET"]
)
def soc_analytics_api():

    try:
        incident_columns = _get_table_columns("incidents")
        ioc_columns = _get_table_columns("iocs")
        evidence_columns = _get_table_columns("evidence")

        total_incidents = 0
        critical = 0
        high = 0
        medium = 0
        low = 0

        if incident_columns:
            row = db.session.execute(
                text('SELECT COUNT(*) FROM "incidents"')
            ).fetchone()
            total_incidents = int(row[0] or 0)

            if "risk_level" in incident_columns:
                rows = db.session.execute(text("""
                    SELECT risk_level, COUNT(*)
                    FROM incidents
                    GROUP BY risk_level
                """)).fetchall()
                for level, count in rows:
                    level = str(level or "").upper()
                    if level == "CRITICAL": critical = int(count)
                    elif level == "HIGH": high = int(count)
                    elif level == "MEDIUM": medium = int(count)
                    elif level == "LOW": low = int(count)

        total_iocs = 0
        if ioc_columns:
            row = db.session.execute(
                text('SELECT COUNT(*) FROM "iocs"')
            ).fetchone()
            total_iocs = int(row[0] or 0)

        total_evidence = 0
        if evidence_columns:
            row = db.session.execute(
                text('SELECT COUNT(*) FROM "evidence"')
            ).fetchone()
            total_evidence = int(row[0] or 0)

        risk_total = critical + high + medium + low
        high_risk = critical + high
        risk_rate = round((high_risk / risk_total) * 100, 2) if risk_total else 0

        return jsonify({
            "success": True,
            "system": "CYBERNEXUS Ω",
            "analytics": {
                "total_incidents": total_incidents,
                "risk_distribution": {
                    "critical": critical,
                    "high": high,
                    "medium": medium,
                    "low": low
                },
                "high_risk_incidents": high_risk,
                "high_risk_percentage": risk_rate,
                "total_iocs": total_iocs,
                "total_evidence": total_evidence
            },
            "status": "operational"
        })

    except Exception as error:
        return jsonify({
            "success": False,
            "error": str(error),
            "system": "CYBERNEXUS Ω",
            "status": "degraded"
        }), 500


@app.route(
    "/api/security-report",
    methods=["GET"]
)
def security_report_api():

    try:
        analytics_response = soc_analytics_api()
        if isinstance(analytics_response, tuple):
            return analytics_response

        payload = analytics_response.get_json()
        if not payload or not payload.get("success"):
            return jsonify(payload or {"success": False}), 500

        analytics = payload.get("analytics", {})
        distribution = analytics.get("risk_distribution", {})
        critical = int(distribution.get("critical", 0))
        high = int(distribution.get("high", 0))
        medium = int(distribution.get("medium", 0))
        low = int(distribution.get("low", 0))

        overall = "LOW"
        if critical > 0:
            overall = "CRITICAL"
        elif high > 0:
            overall = "HIGH"
        elif medium > 0:
            overall = "MEDIUM"

        return jsonify({
            "success": True,
            "system": "CYBERNEXUS Ω",
            "report": {
                "title": "CYBERNEXUS Ω Security Operations Report",
                "overall_risk": overall,
                "total_incidents": analytics.get("total_incidents", 0),
                "critical_incidents": critical,
                "high_incidents": high,
                "medium_incidents": medium,
                "low_incidents": low,
                "total_iocs": analytics.get("total_iocs", 0),
                "total_evidence": analytics.get("total_evidence", 0),
                "high_risk_percentage": analytics.get("high_risk_percentage", 0),
                "recommendation": (
                    "Prioritize critical and high-risk incidents for immediate investigation."
                    if (critical + high) > 0
                    else "Continue routine monitoring and incident correlation."
                )
            },
            "status": "operational"
        })

    except Exception as error:
        return jsonify({
            "success": False,
            "error": str(error),
            "system": "CYBERNEXUS Ω",
            "status": "degraded"
        }), 500


# ============================================================
# START SERVER
# ============================================================

if __name__ == "__main__":

    print("=" * 60)

    print(
        "        CYBERNEXUS Ω SECURITY PLATFORM"
    )

    print("=" * 60)

    print(
        "Dashboard   : http://127.0.0.1:5000"
    )

    print(
        "Health      : http://127.0.0.1:5000/health"
    )

    print(
        "API         : http://127.0.0.1:5000/api"
    )

    print(
        "Database    : http://127.0.0.1:5000/api/database"
    )

    print(
        "Correlation : http://127.0.0.1:5000/api/correlate"
    )

    print(
        "Incident    : http://127.0.0.1:5000/api/incident"
    )

    print(
        "Graph       : http://127.0.0.1:5000/api/graph"
    )

    print(
        "Evidence    : http://127.0.0.1:5000/api/evidence"
    )

    print(
        "IOC         : http://127.0.0.1:5000/api/ioc"
    )

    print("=" * 60)

    app.run(

        host="127.0.0.1",

        port=5000,

        debug=False,

        use_reloader=False

    )