from flask import Flask, render_template, request, jsonify

from detection.url_detector import analyze_url
from detection.file_detector import analyze_file
from detection.email_detector import analyze_email

from core.risk_engine import calculate_unified_risk
from core.correlation_engine import correlate_security_signals
from core.incident_orchestrator import run_incident_orchestration

from graph.knowledge_graph import build_incident_graph

from forensics.evidence_ledger import (
    add_evidence,
    get_evidence,
    verify_ledger
)

import os
import tempfile
import json

from sqlalchemy import text

from database.models import (
    db,
    initialize_database
)


# ============================================================
# APPLICATION
# ============================================================

app = Flask(__name__)


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

BASE_DIR = os.path.abspath(
    os.path.dirname(__file__)
)

DATABASE_DIR = os.path.join(
    BASE_DIR,
    "database"
)

DATABASE_FILE = os.path.join(
    DATABASE_DIR,
    "cybernexus.db"
)

os.makedirs(
    DATABASE_DIR,
    exist_ok=True
)


app.config["SQLALCHEMY_DATABASE_URI"] = (
    "sqlite:///"
    + DATABASE_FILE.replace("\\", "/")
)

app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False


# Initialize database
initialize_database(app)


# ============================================================
# DATABASE HELPERS
# ============================================================

def _get_table_columns(table_name):
    """
    Read SQLite table columns dynamically.

    This keeps database persistence compatible with the
    existing CyberNexus database schema.
    """

    try:

        result = db.session.execute(
            text(
                f"PRAGMA table_info({table_name})"
            )
        )

        rows = result.fetchall()

        return [
            row[1]
            for row in rows
        ]

    except Exception:

        return []


def _safe_json(value):
    """
    Convert Python objects into JSON strings
    when necessary.
    """

    if value is None:
        return None

    if isinstance(
        value,
        (dict, list, tuple)
    ):

        try:

            return json.dumps(
                value,
                ensure_ascii=False
            )

        except Exception:

            return str(value)

    return value


def _insert_matching_columns(
    table_name,
    values
):
    """
    Insert only values whose column names actually
    exist in the SQLite table.

    This prevents database schema mismatch errors.
    """

    columns = _get_table_columns(
        table_name
    )

    if not columns:
        return False

    insert_values = {}

    for key, value in values.items():

        if key in columns:

            insert_values[key] = (
                _safe_json(value)
            )

    if not insert_values:
        return False

    column_names = ", ".join(
        f'"{column}"'
        for column in insert_values.keys()
    )

    parameter_names = ", ".join(
        f":{column}"
        for column in insert_values.keys()
    )

    query = text(
        f"""
        INSERT INTO "{table_name}"
        ({column_names})
        VALUES
        ({parameter_names})
        """
    )

    db.session.execute(
        query,
        insert_values
    )

    return True


def _persist_incident(
    orchestration_result
):
    """
    Persist an incident generated by the
    Incident Orchestrator into SQLite.
    """

    if not isinstance(
        orchestration_result,
        dict
    ):
        return False

    incident = (
        orchestration_result.get(
            "incident"
        )
        or {}
    )

    if not isinstance(
        incident,
        dict
    ):
        incident = {}

    incident_id = (
        incident.get("incident_id")
        or orchestration_result.get(
            "incident_id"
        )
    )

    if not incident_id:
        return False

    try:

        # Prevent duplicate incident records
        columns = _get_table_columns(
            "incidents"
        )

        if "incident_id" in columns:

            existing = db.session.execute(
                text(
                    """
                    SELECT incident_id
                    FROM incidents
                    WHERE incident_id = :incident_id
                    LIMIT 1
                    """
                ),
                {
                    "incident_id":
                        incident_id
                }
            ).fetchone()

            if existing:

                return True

        unified = (
            orchestration_result.get(
                "unified_risk"
            )
            or {}
        )

        correlation = (
            orchestration_result.get(
                "correlation"
            )
            or {}
        )

        values = {

            "incident_id":
                incident_id,

            "incident_level":
                incident.get(
                    "incident_level"
                ),

            "risk_level":
                (
                    unified.get(
                        "overall_level"
                    )
                    if isinstance(
                        unified,
                        dict
                    )
                    else None
                ),

            "risk_score":
                (
                    unified.get(
                        "overall_score"
                    )
                    if isinstance(
                        unified,
                        dict
                    )
                    else None
                ),

            "correlation_score":
                incident.get(
                    "correlation_score"
                ),

            "signal_count":
                incident.get(
                    "signal_count"
                ),

            "high_risk_signal_count":
                incident.get(
                    "high_risk_signal_count"
                ),

            "status":
                "OPEN",

            "severity":
                incident.get(
                    "incident_level"
                ),

            "description":
                (
                    "CyberNexus Ω correlated "
                    "security incident"
                ),

            "data":
                orchestration_result

        }

        # Add correlation values if available
        if isinstance(
            correlation,
            dict
        ):

            values[
                "correlation_score"
            ] = correlation.get(
                "correlation_score",
                values.get(
                    "correlation_score"
                )
            )

        inserted = _insert_matching_columns(
            "incidents",
            values
        )

        if inserted:

            db.session.commit()

        return inserted

    except Exception as error:

        db.session.rollback()

        print(
            "[DATABASE] Incident persistence warning:",
            error
        )

        return False


def _persist_evidence(
    evidence_record
):
    """
    Persist an evidence record into SQLite.

    The original tamper-evident evidence ledger
    continues to operate independently.
    """

    if not isinstance(
        evidence_record,
        dict
    ):
        return False

    try:

        values = {

            "evidence_id":
                evidence_record.get(
                    "evidence_id"
                ),

            "evidence_type":
                evidence_record.get(
                    "evidence_type"
                ),

            "source":
                evidence_record.get(
                    "source"
                ),

            "risk_score":
                evidence_record.get(
                    "risk_score"
                ),

            "risk_level":
                evidence_record.get(
                    "risk_level"
                ),

            "evidence_hash":
                (
                    evidence_record.get(
                        "evidence_hash"
                    )
                    or evidence_record.get(
                        "hash"
                    )
                ),

            "ledger_hash":
                evidence_record.get(
                    "ledger_hash"
                ),

            "data":
                evidence_record

        }

        inserted = _insert_matching_columns(
            "evidence",
            values
        )

        if inserted:

            db.session.commit()

        return inserted

    except Exception as error:

        db.session.rollback()

        print(
            "[DATABASE] Evidence persistence warning:",
            error
        )

        return False


# ============================================================
# DASHBOARD
# ============================================================

@app.route("/")
def dashboard():

    return render_template(
        "dashboard.html"
    )


# ============================================================
# HEALTH
# ============================================================

@app.route("/health")
def health():

    database_status = "unknown"

    try:

        db.session.execute(
            text("SELECT 1")
        )

        database_status = "connected"

    except Exception:

        database_status = "error"

    return jsonify({

        "status":
            "operational",

        "system":
            "CYBERNEXUS Ω",

        "version":
            "1.0.0",

        "database":
            database_status

    })


# ============================================================
# API INFORMATION
# ============================================================

@app.route("/api")
def api_info():

    return jsonify({

        "system":
            "CYBERNEXUS Ω",

        "status":
            "operational",

        "database":
            "SQLite",

        "database_file":
            "database/cybernexus.db",

        "endpoints": {

            "health":
                "/health",

            "url_analysis":
                "/api/analyze-url",

            "file_analysis":
                "/api/analyze-file",

            "email_analysis":
                "/api/analyze-email",

            "unified_risk":
                "/api/unified-risk",

            "correlation":
                "/api/correlate",

            "incident":
                "/api/incident",

            "graph":
                "/api/graph",

            "add_evidence":
                "/api/evidence",

            "get_evidence":
                "/api/evidence",

            "verify_evidence":
                "/api/evidence/verify"

        }

    })


# ============================================================
# URL ANALYSIS
# ============================================================

@app.route(
    "/api/analyze-url",
    methods=["POST"]
)
def analyze_url_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url = (
        data.get(
            "url",
            ""
        )
        .strip()
    )

    if not url:

        return jsonify({

            "success":
                False,

            "error":
                "URL is required."

        }), 400

    try:

        result = analyze_url(
            url
        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# FILE ANALYSIS
# ============================================================

@app.route(
    "/api/analyze-file",
    methods=["POST"]
)
def analyze_file_api():

    if "file" not in request.files:

        return jsonify({

            "success":
                False,

            "error":
                "No file uploaded."

        }), 400

    uploaded_file = (
        request.files["file"]
    )

    if not uploaded_file.filename:

        return jsonify({

            "success":
                False,

            "error":
                "Filename is missing."

        }), 400

    temp_path = None

    try:

        suffix = os.path.splitext(
            uploaded_file.filename
        )[1]

        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=suffix
        ) as temp_file:

            uploaded_file.save(
                temp_file.name
            )

            temp_path = (
                temp_file.name
            )

        result = analyze_file(
            temp_path
        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500

    finally:

        if (
            temp_path
            and os.path.exists(
                temp_path
            )
        ):

            try:

                os.remove(
                    temp_path
                )

            except OSError:

                pass


# ============================================================
# EMAIL ANALYSIS
# ============================================================

@app.route(
    "/api/analyze-email",
    methods=["POST"]
)
def analyze_email_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    email_text = data.get(
        "email",
        ""
    )

    sender = data.get(
        "sender"
    )

    if not email_text:

        return jsonify({

            "success":
                False,

            "error":
                "Email content is required."

        }), 400

    try:

        result = analyze_email(
            email_text,
            sender
        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# UNIFIED RISK
# ============================================================

@app.route(
    "/api/unified-risk",
    methods=["POST"]
)
def unified_risk_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    try:

        result = calculate_unified_risk(

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# CORRELATION ENGINE
# ============================================================

@app.route(
    "/api/correlate",
    methods=["POST"]
)
def correlate_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    try:

        result = correlate_security_signals(

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        return jsonify({

            "success":
                True,

            "result":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# INCIDENT ORCHESTRATOR
# ============================================================

@app.route(
    "/api/incident",
    methods=["POST"]
)
def incident_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    if not any([

        url_result,
        file_result,
        email_result

    ]):

        return jsonify({

            "success":
                False,

            "error":
                "At least one security signal is required."

        }), 400

    try:

        result = run_incident_orchestration(

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        # ====================================================
        # DATABASE PERSISTENCE
        # ====================================================

        database_saved = (
            _persist_incident(
                result
            )
        )

        if isinstance(
            result,
            dict
        ):

            result[
                "database"
            ] = {

                "saved":
                    database_saved,

                "database_file":
                    "database/cybernexus.db"

            }

        return jsonify(
            result
        )

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# KNOWLEDGE GRAPH
# ============================================================

@app.route(
    "/api/graph",
    methods=["POST"]
)
def graph_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    incident_id = data.get(

        "incident_id",

        "UNKNOWN-INCIDENT"

    )

    url_result = data.get(
        "url_result"
    )

    file_result = data.get(
        "file_result"
    )

    email_result = data.get(
        "email_result"
    )

    try:

        graph = build_incident_graph(

            incident_id=
                incident_id,

            url_result=
                url_result,

            file_result=
                file_result,

            email_result=
                email_result

        )

        return jsonify({

            "success":
                True,

            "result":
                graph

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# ADD EVIDENCE
# ============================================================

@app.route(
    "/api/evidence",
    methods=["POST"]
)
def add_evidence_api():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    evidence_type = data.get(

        "evidence_type",

        "UNKNOWN"

    )

    source = data.get(

        "source",

        "Unknown"

    )

    evidence = data.get(

        "evidence",

        {}

    )

    risk_score = data.get(

        "risk_score",

        0

    )

    risk_level = data.get(

        "risk_level",

        "LOW"

    )

    try:

        record = add_evidence(

            evidence_type=
                evidence_type,

            source=
                source,

            evidence=
                evidence,

            risk_score=
                risk_score,

            risk_level=
                risk_level

        )

        database_saved = (
            _persist_evidence(
                record
            )
        )

        return jsonify({

            "success":
                True,

            "record":
                record,

            "database":
                {

                    "saved":
                        database_saved,

                    "database_file":
                        "database/cybernexus.db"

                }

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# GET EVIDENCE
# ============================================================

@app.route(
    "/api/evidence",
    methods=["GET"]
)
def get_evidence_api():

    try:

        records = get_evidence()

        return jsonify({

            "success":
                True,

            "records":
                records,

            "count":
                len(records)

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# VERIFY EVIDENCE
# ============================================================

@app.route(
    "/api/evidence/verify",
    methods=["GET"]
)
def verify_evidence_api():

    try:

        result = verify_ledger()

        return jsonify({

            "success":
                True,

            "verification":
                result

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "error":
                str(error)

        }), 500


# ============================================================
# DATABASE STATUS
# ============================================================

@app.route(
    "/api/database",
    methods=["GET"]
)
def database_status_api():

    try:

        tables = []

        result = db.session.execute(
            text(
                """
                SELECT name
                FROM sqlite_master
                WHERE type='table'
                ORDER BY name
                """
            )
        )

        for row in result.fetchall():

            tables.append(
                row[0]
            )

        return jsonify({

            "success":
                True,

            "database":
                "SQLite",

            "file":
                DATABASE_FILE,

            "status":
                "connected",

            "tables":
                tables

        })

    except Exception as error:

        return jsonify({

            "success":
                False,

            "database":
                "SQLite",

            "status":
                "error",

            "error":
                str(error)

        }), 500


# ============================================================
# START SERVER
# ============================================================

if __name__ == "__main__":

    print("=" * 60)

    print(
        "        CYBERNEXUS Ω SECURITY PLATFORM"
    )

    print("=" * 60)

    print(
        "Dashboard   : http://127.0.0.1:5000"
    )

    print(
        "Health      : http://127.0.0.1:5000/health"
    )

    print(
        "API         : http://127.0.0.1:5000/api"
    )

    print(
        "Database    : http://127.0.0.1:5000/api/database"
    )

    print(
        "Correlation : http://127.0.0.1:5000/api/correlate"
    )

    print(
        "Incident    : http://127.0.0.1:5000/api/incident"
    )

    print(
        "Graph       : http://127.0.0.1:5000/api/graph"
    )

    print(
        "Evidence    : http://127.0.0.1:5000/api/evidence"
    )

    print("=" * 60)

    app.run(

        host="127.0.0.1",

        port=5000,

        debug=False,

        use_reloader=False

    )